### ISSUE TITLE
Allow change script 'Activate' into On/Off 

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#101]
HI

Is it in any way possible to have the Activate button change into something more reflective of the action of the script it activates?
eg i have several On and Off scripts, i would really like to be able to change that.

![schermafbeelding 2018-02-12 om 11 20 03](https://user-images.githubusercontent.com/33354141/36092173-b70d3bde-0fe6-11e8-9180-299e012afea8.jpg)

It would really be even better if the Font color could be changed too, or is that already possible using the theme I already have in place (don't know the object name of the Activate-button) 
A pointer to documentation on the various interface parts would be very much appreciated. 
Thanks,
Cheers,
Marius

**Comment by tringler** [comment]
You can try to override the state by:

```
script.auitorium_on:
  friendly_name: Audio Auditorium On
  templates:
    state: return 'Play';
```

```
script.auitorium_off:
  friendly_name: Audio Auditorium Off
  templates:
    state: return 'Stop';
```

If you want to summarize both into one line you can try my state-card:
https://github.com/tringler/hass-custom-ui_scenes

It's like:
![grafik](https://user-images.githubusercontent.com/4985268/36850965-5c650d94-1d68-11e8-90a2-36a4faa42503.png)

**Comment by hvbhome** [comment]
Cool Thanks!
Would you care to show or share the code to do so? Been looking at your docs but still missing out on the correct setup and syntax for my example.

**Comment by hvbhome** [comment]
Extra: would ‘buttons’ in stead of words be possible too?

**Comment by tringler** [comment]
I would prefer if you can open a issue in repo regarding my state card, because I don't want to spam this repo with bugs of my repo.

Basically you cannot mix up configs from my state card with the config of custom-ui state card. This is not valid:

```
          - entity: script.sw_tv_auditorium_force_on
            friendly_name: Tv Auditorium  #define icon and friendly_name or both
            icon: mdi:television #define icon and friendly_name or both
            state: binary_sensor.tv_auditorium # the binary sensor to determine the current state
            templates:
              state: return 'On';
````

If you use the custom-ui state card you can use the templates config section. If you use my state card you can use my config section (entity, icon, state, etc.)

Here you are my harmony example: (Yes, there is a typo - Thanks)

```
group.livingroom_harmony:
  friendly_name: Harmony
  icon: mdi:television
  custom_ui_state_card: state-card-custom_scene
  config:
    entities:
      - entity: script.remote_livingroom_harmony_entertain
        friendly_name: TV
        state: binary_sensor.harmony_entertain
      - entity: script.remote_livingroom_harmony_ps4
        friendly_name: PS4
        state: binary_sensor.harmony_ps4
      - entity: script.remote_livingroom_harmony_firetv
        friendly_name: FTV
        state: binary_sensor.harmony_firetv
      - entity: script.remote_livingroom_harmony_music
        friendly_name: Music
        state: binary_sensor.harmony_music
      - entity: script.remote_livingroom_harmony_turn_off
        friendly_name: Power Off
        state: binary_sensor.dummy_always_off
```

You can use button or text or you can use buttons and texted based on which entries you have - Just define `friendly_name` or `icon` or both.

Regards, Thomas

**Comment by hvbhome** [comment]
sure, done, thanks:

https://github.com/tringler/hass-custom-ui_scenes/issues/1

**Comment by andrey-git** [comment]
Regarding mixing my customui with templating with other cards: you can do it by using secondary custom UI : https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#secondary-customui

**Comment by hvbhome** [comment]
thanks @andrey-git ,

I've changed into this:

```
group.force_aa:
  friendly_name: Audio Auditorium
  icon: mdi:speaker
  state_card_custom_ui_secondary: state-card-custom_scene
  config:
    entities:
      - entity: script.sw_audio_auditorium_force_off
        friendly_name: Off
        state: binary_sensor.audio_auditorium
      - entity: script.sw_audio_auditorium_force_on
        friendly_name: On
        state: binary_sensor.audio_auditorium

group.force_tva:
  friendly_name: Tv Auditorium
  icon: mdi:television
  state_card_custom_ui_secondary: state-card-custom_scene
  config:
    entities:
      - entity: script.sw_tv_auditorium_force_off
        friendly_name: Off
        state: binary_sensor.tv_auditorium
      - entity: script.sw_tv_auditorium_force_on
        friendly_name: On
        state: binary_sensor.tv_auditorium
```

but still no appearing of these groups...

**Comment by hvbhome** [comment]
not sure how to quote in this GitHub messages, but @andrey-git:

you were dead right with your remark on the secondary custom-ui. I've detailed the results in this case here: https://github.com/tringler/hass-custom-ui_scenes/issues/1#issuecomment-370555052

thanks for these wonderful options!

**Comment by hvbhome** [comment]
@andrey-git 
Templating a them to this seems not possible? 

```
homeassistant:
  customize:
    group.iungo_force_aa:
      friendly_name: Audio Auditorium
      templates: 
        theme: >
            {% if is_state('sensor.audio_auditorium_state', 'on') %} 'green'
            {% else %} 'grey'
            {%- endif %}
      icon: mdi:speaker
      state_card_custom_ui_secondary: state-card-custom_scene
      config:
        entities:
          - entity: script.audio_auditorium_force_off
            friendly_name: 'Off'
            state: sensor.audio_auditorium_state
          - entity: script.audio_auditorium_force_on
            friendly_name: 'On'
            state: sensor.audio_auditorium_state
          - entity: script.audio_auditorium_state
            friendly_name: 'State'
```
Could it be this fails because i am in fact trying to template a Group? Is that even possible. With @tringler 's scene card this Group is displayed as a single line I would like to template along the state of the entity it represents, in this case a switch:

![schermafbeelding 2018-03-07 om 11 37 33](https://user-images.githubusercontent.com/33354141/37087919-fd871e1e-21fb-11e8-95ed-b00111337f6c.jpg)

As it stands, both buttons take the color of the sensor, which is not yet my desired outcome, and that might change, talking to @tringler about that. 
Theming the Audio Auditorium line in this case is a question forth Custom-ui? 

Hope you can have a look please,
Cheers,
Marius
