### ISSUE TITLE
[Feature request] Add confirm_controls+confirm_controls_show_lock for script domain

### ISSUE THREAD

**Issue by pplucky** [andrey-git/home-assistant-custom-ui#107]
**Relevant `configuration.yaml` entries:**
```yaml
customize_glob:
  script.*:
    can_cancel: false
    custom_ui_state_card: state-card-custom-ui

customize:
  script.hasspi_reboot:
    icon: mdi:raspberrypi
    can_cancel: true
    confirm_controls_show_lock: true
```

Scripts without any customization or with can_cancel: true, are actually toggles. Still then, confirm_controls and confirm_controls_show_lock do not seem to work.

![image](https://user-images.githubusercontent.com/16407309/36391354-0aa82422-159e-11e8-94eb-7b892d0a91a2.png)

Is this something that can be added?
