### ISSUE TITLE
State templating not working correctly

### ISSUE THREAD

**Issue by fanaticDavid** [andrey-git/home-assistant-custom-ui#110]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Firefox 58 & Chrome 64

**CustomUI version:** 20180126

**Home Assistant release (`hass --version`):** 0.63.3

**Problem-relevant `configuration.yaml` entries:**
```yaml
sensor.*_ups_battery_runtime:
  friendly_name: "Battery runtime"
  icon: mdi:timelapse
  templates:
    state: ${Math.round(parseInt(state) / 60)}
    unit_of_measurement: 'minutes'
```

**Problem-relevant Home Assistant log entries:**
```
none
```

**Any errors from browser Javascript console:**
```
nothing relevant, as far as I can tell
```

### Issue
I have two sensors that read the runtime of 2 UPS batteries in seconds. For readability, I am trying to convert this to minutes, without the use of a template sensor. When templating the `state` to accomplish this, something quirky happens:

This is how it shows up in the main UI:

<img width="416" alt="schermafbeelding 2018-02-24 om 08 58 41" src="https://user-images.githubusercontent.com/20402931/36627294-0be5c316-1941-11e8-986b-34b49fe12b44.png">

The value of 1 minute is wrong, as shown in the more-info dialog:

<img width="377" alt="schermafbeelding 2018-02-24 om 08 58 56" src="https://user-images.githubusercontent.com/20402931/36627300-1a1c095e-1941-11e8-8647-fe4a74a26e8d.png">

The dev tools confirm what is shown in the more-info dialog:

<img width="703" alt="schermafbeelding 2018-02-24 om 09 00 42" src="https://user-images.githubusercontent.com/20402931/36627322-5045e73e-1941-11e8-8551-6fa1781c9881.png">

It seems that when templating `state`, the template is applied twice (once on the original state, and then again on the templated state). I've had a similar experience with templating a textual `state`, for which I resorted to using `_stateDisplay` instead. I explained that previously [here](https://github.com/andrey-git/home-assistant-custom-ui/issues/97#issuecomment-362862129).
If I use `_stateDisplay: ${Math.round(parseInt(state) / 60) + ' minutes'}` instead of templating `state` in the code above, then the state shows up just fine.

In closing, I do have a related question: does templating `state` actually alter the values saved by the Home Assistant recorder? My money is on 'no' (as this is a **UI**) which means I might have to resort to using template sensors for these sensors anyway rather than Custom UI. I figured I'd still report this apparent bug since it has come up for me a few times now.

**Comment by fanaticDavid** [comment]
As stated above, I get the same issue when templating a textual `state`:

```yaml
sensor.*_ups_status_data:
  friendly_name: "Status"
  icon: mdi:car-battery
  templates:
    # _stateDisplay: if (state.substring(0, 2) === 'OL') return 'Online'; else return 'On battery';
    state: if (state.substring(0, 2) === 'OL') return 'Online'; else return 'On battery';
```

The resulting `state` at a glance:

<img width="419" alt="schermafbeelding 2018-02-24 om 09 53 47" src="https://user-images.githubusercontent.com/20402931/36627803-bac14822-1948-11e8-8cf5-361054819396.png">

And the more-info dialog:

<img width="375" alt="schermafbeelding 2018-02-24 om 09 54 09" src="https://user-images.githubusercontent.com/20402931/36627807-c5b3787c-1948-11e8-861a-b340938b7545.png">

Using `_stateDisplay` instead works just fine.
