### ISSUE TITLE
Badges is clipping into one and other with 0.63.3 ->

### ISSUE THREAD

**Issue by bhaap** [andrey-git/home-assistant-custom-ui#112]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

Chrome - 64

20180216

0.63.3

**Problem-relevant `configuration.yaml` entries:**
```yaml
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    sensor.temperatur_koket:
      state_card_mode: badges
    sensor.ljus_koket:
      state_card_mode: badges
    sensor.jordfuktighet_koket:
      state_card_mode: badges
    sensor.vaxtnaring_koket:
      state_card_mode: badges
    sensor.*_vardagsrummet:
      state_card_mode: badges
    sensor.*_kok:
      state_card_mode: badges
    sensor.temperatur_pannvatten:
      state_card_mode: badges
    sensor.*_vardagsrum:
      state_card_mode: badges
    sensor.*_hall_uppe:
      state_card_mode: badges
    sensor.*_dahlias_sovrum:
      state_card_mode: badges
    sensor.*_kammare:
      state_card_mode: badges
```
<img width="388" alt="skarmavbild 2018-02-25 kl 17 08 36" src="https://user-images.githubusercontent.com/2168003/36643661-2f74c318-1a4f-11e8-802d-5775cd17524b.png">
