### ISSUE TITLE
issue customizing badges and border independently 

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#118]
If this is not the correct place, apologize.

Question: is it impossible to customize the label-badge-red indecently from the label-badge-border-color? 
I try to set these, but no matter what i try, the label-badge-red always colors both the badge and the border. Also, text in the label below the badge always white, no matter what is set in the label-badge-text-color. Would be so nice if this is cleared-up, so we can set as desired. Might be possible already, can not find any hints whatsoever...

example:

```
green_badge:
  label-badge-red: green
  label-badge-border-color: lightgrey
  label-badge-background-color: white
  label-badge-text-color: green
```

shows as:

![schermafbeelding 2018-03-01 om 23 51 36](https://user-images.githubusercontent.com/33354141/36874265-864981f6-1dab-11e8-9856-d9ee65fc6fda.jpg)
no grey border....

thx,
Marius
