### ISSUE TITLE
Content Aware Friendly Name not working on group names.

### ISSUE THREAD

**Issue by tbrasser** [andrey-git/home-assistant-custom-ui#12]
I tried this:
```
group.verlichting_woonkamer:
  friendly_name: Verlichting Woonkamer
  friendly_names:
    group.verlichting: Woonkamer
    group.woonkamer: Verlichting
```
Which doesn't seem to work.

It does work (as expected) on lights within groups.
