### ISSUE TITLE
Hude from default view: badges reappear as unordered entities

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#120]
HI,

Trying the https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#hiding-entities-from-default-view-tab hide entities from default view functionality on a few groups makes their separate entities show up again on the Homepage as unordered entities:
![schermafbeelding 2018-03-04 om 16 57 04](https://user-images.githubusercontent.com/33354141/36947504-1bbc498a-1fcd-11e8-8c24-42a884d7f39a.jpg)

```
fixerio:
  name: Fixer.io
  icon: mdi:currency-eur
  entities:
    - sensor.euro__great_britain_pound
    - sensor.euro__indonesia_rupia
    - sensor.euro__us_dollar

```
Is this expected behavior?
