### ISSUE TITLE
Top of the page badges don

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#121]
Hello,

if I use the by-group templating it will not apply for top of the page badges.

* It works if I remove the by-group templating part and just use templates
* The error only applies to top of the page badges

### Checklist
- [ ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [ ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [ ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 

**CustomUI version:** 20180216

**Home Assistant release (`hass --version`):** 0.65.3

**Problem-relevant `configuration.yaml` entries:**
```yaml
livingroom:
  view: yes
  name: Wohnzimmer
  icon: mdi:television
  entities:
    - binary_sensor.livingroom_climate_windowshutter  

binary_sensor.livingroom_climate_windowshutter:
  icon: mdi:glassdoor
  friendly_name: Wohnzimmerfenster
  group:
    group.livingroom:
        templates:
          theme: if (entities['binary_sensor.livingroom_climate_windowshutter'].state === 'on') return 'active';
          friendly_name: if (entities['binary_sensor.livingroom_climate_windowshutter'].state === 'on') return 'Seit ' + (entities['sensor.livingroom_climate_windowshutter_openingtime'].state) + ' Minuten geöffnet'; else return 'Fenster';
  state_card_mode: badges

```
