### ISSUE TITLE
where to put hide_attributes and columns: ?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#123]
HI,
saw these customizations but am unsure where to put them. I use the /config/www/custom_ui setup, and have a customize_glob.yaml.
Like to hide the   `custom_ui_state_card: state-card-custom-ui` on all entities being shown.

tried it in the _glob, below the 

```
"*.*":
  custom_ui_state_card: state-card-custom-ui


  hide_attributes:
    - custom_ui_state_card
  columns: 
    - 30
    - 500
    - 1000
    - 1500

```

with the result on all entities the `hide_attributes` is showing, next to the   `custom_ui_state_card: state-card-custom-ui` id wanted to hide ;-)

also,

the columns setting seems out of place here.

Where do we place both please?
Thanks,
Marius
