### ISSUE TITLE
Theme change not working on Firefox and Edge

### ISSUE THREAD

**Issue by bieniu** [andrey-git/home-assistant-custom-ui#133]
I use Custom UI (local install with Customizer component) to change theme of sensors icons. It works perfectly on Chrome/Opera but on Firefox and Edge it’s completely ignored.

### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Firefox 60.0.1

**CustomUI version:** 20180521

**Home Assistant release (`hass --version`):** 0.69.1

**Problem-relevant `configuration.yaml` entries:**
```
homeassistant:
  customize_glob:
    'binary_sensor.*_status':
      device_class: connectivity
      custom_ui_state_card: state-card-custom-ui
      theme: 'grey'

frontend:
  javascript_version: auto
  themes:
    grey:
      paper-item-icon-color: '#969696'
      paper-item-icon-active-color: '#44739e'

customizer:
  custom_ui: local
```

**Any errors from browser Javascript console:** no errors
