### ISSUE TITLE
Extra data template not working for climate cards

### ISSUE THREAD

**Issue by schmittx** [andrey-git/home-assistant-custom-ui#138]
[Documentation](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/features.md#you-can-add-extra-data-below-the-entity-name) says that `extra_data_template` should work for climate cards, but it's not working for me. See configuration below and screenshots of result.

![image](https://user-images.githubusercontent.com/630673/41951795-a3f15d50-799a-11e8-8814-4823592f352b.png)
![image](https://user-images.githubusercontent.com/630673/41951808-b95dcf66-799a-11e8-88b9-70fd27d093bd.png)

### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:**  Safari 11.1.1 and Chrome 67.0.3396.99

**CustomUI version:**  20180625

**Home Assistant release (`hass --version`):**  0.72.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
customizer:
  custom_ui: hosted
homeassistant:
  customize_glob:
    climate.*:
      custom_ui_state_card: state-card-custom-ui
      extra_data_template: >
        if (attributes.away_mode) return "Away Mode: " + attributes.away_mode; else return null;
```

**Problem-relevant Home Assistant log entries:** None

**Any errors from browser Javascript console:** None
