### ISSUE TITLE
min/max/pin doesn't work with climate components

### ISSUE THREAD

**Issue by seidler2547** [andrey-git/home-assistant-custom-ui#141]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Firefox

**CustomUI version:** 
CustomUI: 20180625
**Home Assistant release (`hass --version`):** 
Home Assistant
0.72.1
**Problem-relevant `configuration.yaml` entries:**
```yaml
  customize_glob:
    climate.*:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      slide_theme:
        min: 16
        max: 28
        pin: true
        off_when_min: false
        report_when_not_changed: false

```

So I put min/max and pin into the config, the slider appears but the limits aren't respected and there is no pin.
