### ISSUE TITLE
extra_data_template no longer working for lock devices

### ISSUE THREAD

**Issue by coreyo** [andrey-git/home-assistant-custom-ui#146]
I just upgraded to
  homeassistant-0.74.2
  Custom UI "20180716"

The following entry in customize.yaml was working until the most recent upgrades:

```
lock.front_door_deadbolt_locked:
  custom_ui_state_card: state-card-custom-ui
  extra_data_template:
    - "Battery: ${entities['zwave.front_door_deadbolt'].attributes.battery_level}%"
    - "if (attributes.lock_status) return 'Lock Status: ' + attributes.lock_status; else return null;"
    - "if (attributes.notification) return 'Last Opened: ' + attributes.notification; else return null;"
```
