### ISSUE TITLE
Vacuum is not affected.

### ISSUE THREAD

**Issue by vidvisionify** [andrey-git/home-assistant-custom-ui#155]
I'm trying to add vacuum status as an extra data template, and battery level as an extra badge. Neither are showing up on either of my vacuums. 

#### Current Example
![Example](https://i.imgur.com/cbfTQhV.png)
#### Expected Behavior
![Expected Behavior](https://i.imgur.com/KqPHpzd.png)

### Checklist
- [✔] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [✔ ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [✔ ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 69
**CustomUI version:** 20180831
**Home Assistant release (`hass --version`):** 0.77.2

**Problem-relevant `customize.yaml` entries:**
```yaml
# Roomba
vacuum.roomba:
  extra_data_template:
  - ${attributes.status}
  extra_badge:  
    entity_id: sensor.roomba_battery

# Ecovacs Vacuum
vacuum.deedee:
  extra_data_template:
  - ${attributes.status}
  extra_badge:  
    entity_id: sensor.deedee_battery

# As shown in Expected Behavior
remote.home_theater:
  extra_data_template:
  - ${attributes.current_activity}
  extra_badge:  
    entity_id: sensor.tv_power
```
