### ISSUE TITLE
Themes set in Custom-ui not recognized in frontend Lovelace

### ISSUE THREAD

**Issue by Mariusthvdb** [andrey-git/home-assistant-custom-ui#163]
### Checklist
- [ ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [ ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [ ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Safari/Chrome/Firefox Mac Mijave

**CustomUI version:** 

20181217
**Home Assistant release (`hass --version`):** 

0.84.3
**Problem-relevant `configuration.yaml` entries:**
```yaml
sensor.huidig_tarief:
  templates:
    icon: >
      if (state === '1') return 'mdi:numeric-1-box-multiple-outline';
      if (state === '2') return 'mdi:numeric-2-box-multiple-outline';
      return 'mdi:fire';
    theme: >
      if (state === '1') return 'green';
      return 'orange';
    _stateDisplay: >
       if (state === '1') return 'Laag';
       return 'Hoog';
```
 and theme:

```
orange:
  primary-text-color: orange
  paper-item-icon-color: orange
  secondary-text-color: orange
  label-badge-background-color: white
  label-badge-text-color: orange
  label-badge-red: orange
  label-badge-border-color: orange
**Problem-relevant Home Assistant log entries:**
```
```

```
no log entries

**Any errors from browser Javascript console:**
```

```
please see: https://github.com/home-assistant/home-assistant-polymer/issues/2366
and https://community.home-assistant.io/t/lovelace-themes-custom-ui/81658/2
