### ISSUE TITLE
extra_badge displays sensor name or "none" on home assistant >0.84.3 (should be hidden)

### ISSUE THREAD

**Issue by thecode** [andrey-git/home-assistant-custom-ui#164]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser (also clear site data from dev panel)
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**CustomUI version:** 20181217

**Home Assistant release (`hass --version`):** 0.84.6

**Problem-relevant `configuration.yaml` entries:**
```yaml
homeassistant:
  customize: 
    cover.dining_room_shutter:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider
      slider_theme:
        pin: true
      extra_badge:
        - attribute: current_position
          unit: "%"
```

**Problem-relevant Home Assistant log entries:**
```
No errors
```

From home assistant version 0.84.5 and above the extra_badge sensor name or 'none' for attribute is displayed in card instead of being hidden

**Home Assistant 0.84.6 sensor name is displayed:**
extra badge sensor:
![image](https://user-images.githubusercontent.com/1858925/50447462-f034ac80-0923-11e9-9f22-dfac3c10e7dc.png)

extra badge attribute:
![image](https://user-images.githubusercontent.com/1858925/50447475-00e52280-0924-11e9-9947-d38c978489a5.png)

**On  Home Assistant 0.84.3 the name is not displayed:**
extra badge sensor:
![image](https://user-images.githubusercontent.com/1858925/50447398-8e744280-0923-11e9-9107-06e6afefda10.png)

extra badge attribute:
![image](https://user-images.githubusercontent.com/1858925/50447413-a77cf380-0923-11e9-8a4e-6b5dfe91a2d0.png)
