### ISSUE TITLE
icon_color template does not work in 0.88

### ISSUE THREAD

**Issue by cklit** [andrey-git/home-assistant-custom-ui#168]
### Checklist
- [x ] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x ] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x ] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome, Version 72.0.3626.109 (Official Build) (64-bit)

**CustomUI version:** 
20190113

**Home Assistant release (`hass --version`):** 
Hass.io 0.88.0

**Problem-relevant `customize.yaml` entries:**
```yaml
sensor.indendoers:
  device_class: temperature
  templates:
    icon_color: 'if (state > 24) return ''rgb(223, 76, 0)''; if (state >= 21 ) return
      ''rgb(12, 135, 102)''; return ''rgb(214, 189, 29)'';'
```

This configuration works in 0.87, but after updating to 0.88 the custom colors does not work.
Possibly due to update on base card in 0.88.

**Comment by rzolau** [comment]
Can confirm the same issue.

**Comment by HACee** [comment]
Same problem here as well.

**Comment by jncanches** [comment]
Same as 169. I debugged it already. Hope Andrew will have time tout update it.

**Comment by Sjeff** [comment]
same issue on version 0.88.1.

**Comment by bratanon** [comment]
It is working. To you all that have this problem, please see your logs. I had some other issues, and by resolving them, this started to work.

**Comment by rhadamantys** [comment]
dito. homeassistant 0.88.1 using chrome

**Comment by josh929800** [comment]
Same issue on version 0.88.1 using any browser.

**Comment by hoangtuit** [comment]
same issue on version 0.88.1

**Comment by varrcan** [comment]
same issue on version 0.88.1

**Comment by WhistleMaster** [comment]
In the mean time, someone found [a solution](https://community.home-assistant.io/t/entity-icon-color-custom-icon-color-based-on-state-customise-icon-color/102789/20) using **hs_color**

**Comment by rzolau** [comment]
This is rather surprising workaround, and as far as I can tell it uses HSV color space (but at least for me) ignores V component...

**Comment by peterhoe** [comment]
@rzolau
same for me, the V or B (or last integer) is ignored (makes no difference what i make that value)

**Comment by cklit** [comment]
> This is rather surprising workaround, and as far as I can tell it uses HSV color space (but at least for me) ignores V component...

Same here. But then again, it IS called hs_color, so I guess it's not false advertising ;) Works as a workaround, but looking forward for the solution :)

**Comment by josh929800** [comment]
I got color working again on my dashboard... via the hs_color workaround with the brightness too... 

I used [http://colorizer.org/](http://colorizer.org/) to convert the RGB into Hue, Saturation, and Brightness. Then I took the (Brightness#/100)*255 = The number you need to give Home Assitant using the separate brightness template. 

Thanks to @WhistleMaster for putting the link here and to @arsaboo for showing his work on how to fix the brightness issue. 
https://community.home-assistant.io/t/customui-discussion-thread/48694/25

```yaml
input_boolean.home:
  templates:
    hs_color: 'if (state === ''on'') return [205,82]; else return [186,12];

      '
    brightness: 'if (state === ''on'') return 209; else return 147;

      '
```
