### ISSUE TITLE
Extra keys not allowed

### ISSUE THREAD

**Issue by thisis-gj** [andrey-git/home-assistant-custom-ui#173]
**CustomUI version:** Latest

**Home Assistant release (`hass --version`):** 0.93.3

**Problem-relevant `configuration.yaml` entries:**
```
homeassistant:
  customize:
    customize_glob:
      light.*:
        custom_ui_state_card: state-card-custom-ui
```

**Problem-relevant Home Assistant log entries:**
```
extra keys not allowed @ data['customize']['customize_glob']
```
```
Uncaught TypeError: Cannot read property 'some' of undefined
```

**Any errors from browser Javascript console:**
```
Access to imported resource at 'https://github.com/andrey-git/home-assistant-custom-ui/releases/download/20171129/state-card-custom-ui-dbg.html' from origin 'http://www. redacted.casa' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by Mariusthvdb** [comment]
customize_glob should have its own entry under `homeassistant:` and you have it under `customize:`
It should be:

```
homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui

  customize:
    thingstocustomize:
```
