### ISSUE TITLE
HA 0.110.2: Extra badge does not show up

### ISSUE THREAD

**Issue by drew1kun** [andrey-git/home-assistant-custom-ui#187]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome 81.0.4044.138 (Official Build) (64-bit)

**CustomUI version:** 
20190518
**Home Assistant release (`hass --version`):** 
0.110.2
**Problem-relevant `configuration.yaml` entries:**
```yaml
customizer:
  custom_ui: local

frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
  - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-dbg.html
  extra_html_url_es5:
  - https://raw.githubusercontent.com/andrey-git/home-assistant-custom-ui/master/state-card-custom-ui-dbg-es5.html

homeassistant:
  customize:
    light.gateway:
      custom_ui_state_card: state-card-custom-ui
      extra_badge:
        entity_id: sensor.gateway_illumination
```

**`ui-lovelace.yaml`**
```yaml
cards:
- type: vertical-stack
  title: Living Room Controls
  show_header_toggle: false
  cards:
  - type: entities
    title: Lights and Switches
    entities:
    - light.gateway
```

Expecting extra badge here:
![Screen Shot 2020-05-26 at 10 30 37 AM](https://user-images.githubusercontent.com/10493450/82872638-fb867000-9f3b-11ea-8336-686f3e338cad.png)

**Problem-relevant Home Assistant log entries:**
```
no any related entires noticed
```

**Any errors from browser Javascript console:**
```
no any related entires noticed... But here is a screenshot just in case..
```
![Screen Shot 2020-05-26 at 11 58 49 AM](https://user-images.githubusercontent.com/10493450/82881494-735a9780-9f48-11ea-8af6-1e2606faff7c.png)

**Comment by Mariusthvdb** [comment]
extra_badge is long gone, and was designed for HA States, not for Lovelace.
btw If you want to keep coloring your icons, you need the state-card-custom-ui.html I changed, which is available in the Pull requests section of this repo. All other files can be taken out.

for your extra badge, you can have a look at https://github.com/benct/lovelace-multiple-entity-row
 which allows you to do this:

<img width="446" alt="Schermafbeelding 2020-05-26 om 12 41 27" src="https://user-images.githubusercontent.com/33354141/82891558-3d201680-9f4e-11ea-9353-9da805653ed8.png">

as for your setup, you should only use this:

```
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
```

or:
```
customizer:
  custom_ui: local
```

and take out all other mentions of state-card in the bits you posted above.

I suggest not using customizer though, because it does nothing more than the frontend option now that the other functionality is no longer use, and it causes a warning in the log you are using an unsupported custom integration...

**Comment by drew1kun** [comment]
Oh, I see... Gotcha.. You are using the multiple-entity-row here.. I am aware of that, just wanted something new, like badge, lol. So the documentation for custom-ui is not clear about the badge.

Thank you very much for clarifying this.

So you mean the only feature of the custom-ui left is colorizing the icons and probably text?
And therefore I can remove everything from my `/config/www/custom_ui/` except `state-card-custom-ui.html` from the following [pull request](https://github.com/andrey-git/home-assistant-custom-ui/pull/185). Is that right?
And so can I remove the `/config/custom_components/customizer` completely then?

Btw, which brand switches are you using here on your screenshot above?

**Comment by Mariusthvdb** [comment]
no, many other things can still be customized using the template functionality custom-ui offers. 
Only specific states ui options are no longer available, simply because homeassisant doesnt use them any longer, or has another way of doing things. Like with the icon_color recently after HA 110.
Eg you can still see a theme via custom-ui on an entity, and the more info window on that entity will show the correct template. Its just that Lovelace doesnt support entity theming... so its useless. for now.

and yes, if you use the frontend method, you can completely remove customizer.

the pull request isn't merged, and probably never will, because the complete repo isn't maintained any longer.

Im am hoping we can have a modern custom-ui.js version anytime in the future, since both Bram and Thomas have been helping me using the legacy custom-ui work with ha 110, and I am sure they see the power ;-)

My switches are Z-wave switches that are connected to HA via Mqtt.

**Comment by drew1kun** [comment]
Gotcha! Thank you for elaborating this... I actually noticed that my battery level icons are not being colorized any longer (((.

I have tried what you suggested, completely removed the customizer and downloaded the `state-card-custom-ui.html` from your repo `patch-1` branch but they are still not colorized (((

Here is what I have:

**configuration.yaml**
```yaml
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
  - /local/custom_ui/state-card-custom-ui.html

homeassistant:
  customize:
    sensor.bedroom_t_h_p_battery:
      custom_ui_state_card: state-card-custom-ui
      templates:
        # Following changes the text color in details window,
        # when clicking on sensor in UI, according to custom themes/alert.yaml:
        theme: if (state <= 10) return 'alert_red'; else if (state <= 30) return 'alert_yellow';
        # Following changes the sensor's lovelace icon color:
        icon_color: >
          if (state <= 10) return 'rgb(220, 76, 64)'; else if (state <= 30) return 'rgb(248, 192, 30)';
```

**themes/alert.yaml**
```yaml
alert_yellow:
  primary-text-color: '#FFC100'     # Solarized Yellow
  paper-item-icon-color: '#FFC100'  # Solarized Yellow
alert_red:
  primary-text-color: '#DC312E'     # Solarized Red
  paper-item-icon-color: '#DC312E'  # Solarized Red
```

Result (still no color - why is that?):
![Screen Shot 2020-05-26 at 2 57 18 PM](https://user-images.githubusercontent.com/10493450/82898139-6bf3b800-9f61-11ea-8e54-701c0abc9c29.png)

But when I click on the sensor icon (it's colorized, so the theme seems to be applied, or am I wrong?):
![Screen Shot 2020-05-26 at 2 57 36 PM](https://user-images.githubusercontent.com/10493450/82898243-95144880-9f61-11ea-9cb9-d71d0d4ad3f3.png)

Any ideas what may be wrong then?

And yes, I know you said that lovelace does not use themes, but why then I see the colorized yellow icon when clicking on sensor?
