### ISSUE TITLE
HA 0.110.2 - Icons are not being colorized

### ISSUE THREAD

**Issue by drew1kun** [andrey-git/home-assistant-custom-ui#188]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome 81.0.4044.138 (Official Build) (64-bit)

**CustomUI version:** 
20190518
**Home Assistant release (`hass --version`):** 
0.110.2
**Problem-relevant `configuration.yaml` entries:**
```yaml
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
  - /local/custom_ui/state-card-custom-ui.html

homeassistant:
  customize:
    sensor.bedroom_t_h_p_battery:
      templates:
        # Following changes the text color in details window,
        # when clicking on sensor in UI, according to custom themes/alert.yaml:
        theme: >
          if (state <= 10) return 'alert_red';
          if (state <= 30) return 'alert_yellow';
          return 'grey';
        # Following changes the sensor's lovelace icon color:
        icon_color: >
          if (state <= 10) return 'rgb(220, 76, 64)';
          if (state <= 30) return 'rgb(248, 192, 30)';
          return 'grey';
```
**themes/alert.yaml**
```yaml
alert_yellow:
  primary-text-color: '#FFC100'     # Solarized Yellow
  paper-item-icon-color: '#FFC100'  # Solarized Yellow
alert_red:
  primary-text-color: '#DC312E'     # Solarized Red
  paper-item-icon-color: '#DC312E'  # Solarized Red
```

Result (icon is not colorized):
![Screen Shot 2020-05-26 at 2 57 18 PM](https://user-images.githubusercontent.com/10493450/83001844-f5b08d80-a014-11ea-8829-fd1c7feb67d8.png)

When I click on the sensor's icon, it's not colorized either:
![Screen Shot 2020-05-26 at 3 35 57 PM](https://user-images.githubusercontent.com/10493450/83003751-6ce72100-a017-11ea-829d-e3ce5efe6599.png)

But when I add `custom_ui_state_card: state-card-custom-ui` so the code looks like this:

```yaml
homeassistant:
  customize:
    sensor.bedroom_t_h_p_battery:
    custom_ui_state_card: state-card-custom-ui 
      templates:
        # Following changes the text color in details window,
        # when clicking on sensor in UI, according to custom themes/alert.yaml:
        theme: >
          if (state <= 10) return 'alert_red';
          if (state <= 30) return 'alert_yellow';
          return 'grey';
```
Then the icons on card still not colorized, but the state is colorized (see, it is yellow now):
![Screen Shot 2020-05-26 at 2 57 36 PM](https://user-images.githubusercontent.com/10493450/83004059-d5360280-a017-11ea-8e3c-870462b1b334.png)

So `theme` works, while `icon_color` does not. I tried to use them simultaneously and one by one - no changes.
 
**Problem-relevant Home Assistant log entries:**
```
nothing I can see
```

**Any errors from browser Javascript console:**

![Screen Shot 2020-05-27 at 1 22 13 PM](https://user-images.githubusercontent.com/10493450/83007949-1bda2b80-a01d-11ea-88d8-93f6108a66ac.png)
