### ISSUE TITLE
REQUEST: Extra Data allow other entities

### ISSUE THREAD

**Issue by kylerw** [andrey-git/home-assistant-custom-ui#19]
While I understand why attributes may be the only option today, example where other entities makes sense:
```
      sensor.dark_sky_temperature:
        friendly_name: Currently
        custom_ui_state_card: custom-ui
        extra_data_template: "{sensor.dark_sky_apparent_temperature}"
```

I can then have one line with Temperature - a 'Currently' with a 'Feels Like' as Extra Data.
