### ISSUE TITLE
Customization is being ignored within paper-buttons-row

### ISSUE THREAD

**Issue by drew1kun** [andrey-git/home-assistant-custom-ui#190]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**CustomUI version:** 
CustomUI: 20200520-adapted-for-HA110+

**Home Assistant release (`hass --version`):** 
0.110.2

**Problem-relevant `configuration.yaml` entries:**
```yaml
frontend:
  extra_module_url:
  - /local/custom_ui/state-card-custom-ui.js

homeassistant:
  customize_domain:
    climate:
      templates:
        icon_color: >
          if (state == 'heat_cool') return '#99AC18';
          if (state == 'heat') return '#F58019';
          if (state == 'cool') return '#268AD2';
          if (state == 'dry') return '#FFC100';
        icon: >
          if (state == 'heat_cool') return 'mdi:sync';
          if (state == 'heat') return 'mdi:fire';
          if (state == 'cool') return 'mdi:snowflake';
          if (state == 'dry') return 'mdi:water-percent';
          if (state == 'fan_only') return 'mdi:fan';
          return 'mdi:air-conditioner';

  customize:
    switch.all_climate_heat_cool:
      templates:
        icon_color: if (state == 'on') return '#99AC18';  # 'rgb(154, 171, 33)';  # Solarized Green
    switch.all_climate_heat:
      templates:
        icon_color: if (state == 'on') return '#F58019';  # 'rgb(245, 128, 25)';  # Orange
    switch.all_climate_cool:
      templates:
        icon_color: if (state == 'on') return '#268AD2';  # 'rgb(76, 154, 218)';  # Solarized Blue
    switch.all_climate_dry:
      templates:
        icon_color: if (state == 'on') return '#FFC100';  # 'rgb(248, 192, 30)';  # Solarized Yellow
```

**ui-lovelace.yaml** - comparison: entities card vs paper-buttons-row (within auto-entities card)
```yaml
...
  - type: entities
    title: Climate
    entities:
    - climate.kitchen_ac
    - climate.bedroom_ac
    footer:
      type: buttons
      entities:
      - switch.all_climate_heat_cool
      - switch.all_climate_heat
      - switch.all_climate_cool
      - switch.all_climate_dry
      - switch.all_climate_power_off

  - type: custom:auto-entities
    card:
      type: entities
      title: Climate
      show_header_toggle: false
    entities:
    - climate.kitchen_ac
    - climate.bedroom_ac
    - type: custom:paper-buttons-row
      buttons:
      - entity: switch.all_climate_heat_cool
        name: false
      - entity: switch.all_climate_heat
        name: false
      - entity: switch.all_climate_cool
        name: false
      - entity: switch.all_climate_dry
        name: false
      - entity: switch.all_climate_power_off
        name: false
...
```

**Result:** 
- Entities card (the above) colorizes switches in accordance with the customization (snowflake is blue).
- Auto-entities (the below) colorizes climate entities in accordance with the customization (snowflake is blue).
- paper-buttons-row (the below row) seems to ignore the customization (snowflake is yellow).

![Screen Shot 2020-06-14 at 1 26 39 PM](https://user-images.githubusercontent.com/10493450/84591022-d81c5a00-ae43-11ea-8d4a-e45700c13db6.png)

**Problem-relevant Home Assistant log entries:**
```

```

**Any errors from browser Javascript console:**
```

```

**Comment by drew1kun** [comment]
tried to put the `paper-buttons-row` into entities card like so:

```yaml
 title: Home Controls
  cards:
  - type: entities
    title: Climate
    entities:
    - climate.kitchen_ac
    - climate.bedroom_ac
    - type: custom:paper-buttons-row
      buttons:
      - entity: switch.all_climate_heat_cool
        name: false
      - entity: switch.all_climate_heat
        name: false
      - entity: switch.all_climate_cool
        name: false
      - entity: switch.all_climate_dry
        name: false
      - entity: switch.all_climate_power_off
        name: false
    footer:
      type: buttons
      entities:
      - switch.all_climate_heat_cool
      - switch.all_climate_heat
      - switch.all_climate_cool
      - switch.all_climate_dry
      - switch.all_climate_power_off
```
Same thing:
![Screen Shot 2020-06-14 at 2 07 02 PM](https://user-images.githubusercontent.com/10493450/84591579-58dd5500-ae48-11ea-9dff-235087f54a00.png)

So I guess there may be a problem with the paper-buttons-row
