### ISSUE TITLE
Display sensor in extra data template

### ISSUE THREAD

**Issue by laurentdinclaux** [andrey-git/home-assistant-custom-ui#27]
I am struggling to display a sensor in an extra_data_template.

This works:

```
homeassistant:
    customize:
        sensor.home_battery_load_watts:
            friendly_name: test
            extra_data_template: "test"
```

These do not:

```
            extra_data_template: '{{ states.sensor.whizbangjr_amps.state }}'
```

```
            extra_data_template: {{ states.sensor.whizbangjr_amps.state }}
```

Note: the bellow non working exemple works as a value_template elsewhere ....
```
            extra_data_template: '{{ states.sensor.whizbangjr_amp.state|int }}'
```

```
            extra_data_template: '{{ entities.sensor.whizbangjr_amp }}'
```
Note: The bellow exemple test won't execute as javascript but show the script literally in the UI "return 'test';"
```
            extra_data_template: >
                return 'test';
```

This won't work either:
```
            extra_data_template: >
                {{states.sensor.whizbangjr_amp}}A
```

Indeed test were made using latest version:

```
$ ./update.sh 
Getting state-card-custom-ui.html
Getting state-card-custom-ui.html.gz
Updated to Custom UI '20170802'
Getting ha-panel-custom-ui.html
Getting ha-panel-custom-ui.html.gz
Updated Panel to '20170802'
Getting __init__.py
File up to date.
Getting services.yaml
File up to date.
```

**Comment by laurentdinclaux** [comment]
Another fail (the badge shows properly, not the extra_data)

```
sensor.home_battery_load_watts:
            friendly_name: test
            extra_data_template: >
                ${attributes.amps + 'A'}
            extra_badge:
                entity_id: sensor.whizbangjr_amps  # Will take precedence over attribute and unit below.
                attribute: amps
                unit: A
                blacklist_states: 0
```

**Comment by andrey-git** [comment]
Those are JavaScript templates evaluated in your browser, not Jinja2 templates which are evaluated server-side and use a different syntax.

I added a clarification to the docs about this.

`${attributes.amps + 'A'}` should work however.

I just tested the following and it worked:
```yaml
    light.study_lights:
      friendly_name: Light stretch-slider break-slider-toggle
      state_card_mode: break-slider-toggle
      stretch_slider: true
      amps: 11
      extra_data_template: >
        ${attributes.amps + 'A'}
```

```
extra_data_template: >
                return 'test';
```
worked fine too.


To make sure last version is loaded properly - open your browser's dev panel (Ctrl+shift+I or F12 on Chrome) - the CustomUI version should be printed in the console.
