### ISSUE TITLE
Custom_ui not showing up correctly on 0.51.1

### ISSUE THREAD

**Issue by arsaboo** [andrey-git/home-assistant-custom-ui#32]
Updated to 0.51.1 and the WemoInsight switch did not appear correctly:
![image](https://user-images.githubusercontent.com/18319734/29250221-a29bf6b4-800c-11e7-84be-e55a3370a43a.png)

I copied the latest files today and here's the configuration of the switch:
```yaml
     switch.wemoinsight:
       custom_ui_state_card: custom-ui
       extra_badge:
         entity_id: sensor.wemopowerused  # Will take precedence over attribute and unit below.
         attribute: power_consumption
         unit: W
         blacklist_states: 0
```
