### ISSUE TITLE
Max and pin attributes not working as expected

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#4]
These custom UI elements are fantastic and thank you very much for them! I hope you create more custom ui elements.

I've run into a couple of problems:

1. Even with max set to 255 the slider in the custom ui. is only able to set the value of brightness up to 100 maximum.
2. With pin set to true I do not see the value as I move the slider.

Tested in both Safari and Chrome on macOS and in Edge on Windows 10.

**Comment by andrey-git** [comment]
Could you paste your custom-ui related config here?

**Comment by mihalski** [comment]
In configuration.yaml:
```
homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: custom_light
    cover.*:
      custom_ui_state_card: custom_cover
```
In customise.yaml:
```
    light.office:
      custom_ui_state_card: custom_light
      state_card_mode: break-slider
      stretch_slider: true
      # extra_data_template: "{power_consumption!=10}W"
      slider_theme:
        min: 1
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false
```
Now here is where I am a bit confused. The entity name doesn't match any entity and yet all the lights have taken on the new customised ui. Is this where I'm messing up?

**Comment by andrey-git** [comment]
All lights will take the customized ui from the
```
homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: custom_light
```
part. (Which is matching all entities with ID starting from `light.`)
If `light.office` is not an actual ID it won't apply anywhere. If it is - the config seems fine.

**Comment by mihalski** [comment]
light.office is not an actual entity_id. Does this mean that the component defaults to pin: false and max: 100 ?

Also, does this mean that to apply this customisation to every light with the desired settings I have to duplicate the entire entry for each light?

**Comment by andrey-git** [comment]
`pin` defaults to `false`, but `max` defaults to 255.

If you want the same options for all your lights - just put them under the `customize_glob:` section:

```
homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: custom_light
      state_card_mode: break-slider
      stretch_slider: true
      # extra_data_template: "{power_consumption!=10}W"
      slider_theme:
        min: 1
        max: 255
        pin: true
        off_when_min: false
        report_when_not_changed: false
```
