### ISSUE TITLE
Need to force refresh before entities show (0.53.)

### ISSUE THREAD

**Issue by Sennevds** [andrey-git/home-assistant-custom-ui#40]
If I restart hass and go to the ui the custom cards don't show(no entities) and in chrome debugger there are a lot of errors about not finding the html file in the custom_ui folder.
After force refresh (ctrl+f5) it works

i'm using the hosted version with folowing configuration
```
customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
      state_card_mode: break-slider-toggle
```
