### ISSUE TITLE
Margin between badges

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#43]
Hello,

is there any possibility to add a margin between multiple badges? For instance that a badge name like "temperature" is not cut to "temperat...?

**Comment by andrey-git** [comment]
Could you attach a screenshot?

**Comment by tringler** [comment]
Here you are:

![image](https://user-images.githubusercontent.com/4985268/30511953-0b7158ea-9ae4-11e7-835d-1583c15e7bfb.png)

**Comment by andrey-git** [comment]
Are you adding `state_card_mode: badges` to each sensor, or is it an inner group, where you added `state_card_mode: badges` to the group?

**Comment by tringler** [comment]
Indeed - It's like:

```
sensor.climate_storage_humidity:
  icon: mdi:water-percent
  friendly_name: Luft
  state_card_mode: badges
  
sensor.climate_storage_temperature:
  icon: mdi:temperature-celsius
  friendly_name: Temperatur
  state_card_mode: badges
```
