### ISSUE TITLE
Themes for badges

### ISSUE THREAD

**Issue by tringler** [andrey-git/home-assistant-custom-ui#44]
Hello,

I don't want to spam your issues section, but it is possible to add support, that I can apply a theme to a badge?

I tried, but it is not applied to my badge.

### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 

**CustomUI version:** 

**Home Assistant release (`hass --version`):** 

**Problem-relevant `configuration.yaml` entries:**
```yaml

kitchen:
  name: Küche
  view: no
  entities:
    - group.kitchen_windowshutter

kitchen_windowshutter:
  view: no
  entities:
    - binary_sensor.climate_kitchen_windowshutter

```

or

```yaml

kitchen:
  name: Küche
  view: no
  entities:
    - binary_sensor.climate_kitchen_windowshutter
```

Customize:
```yaml
binary_sensor.climate_kitchen_windowshutter:
  icon: mdi:glassdoor
  friendly_name: Fenster
  theme_template: >
    if (entities['binary_sensor.climate_livingroom_windowshutter'].state === 'on') return 'yellow'; else return 'default';
  extra_data_template: >
     if (entities['binary_sensor.climate_livingroom_windowshutter'].state === 'off') return null; else return Seit (entities['sensor.climate_livingroom_windowshutter_openingtime'].state) Minuten offen;
  state_card_mode: badges

group.kitchen_windowshutter:
  icon: mdi:glassdoor
  friendly_name: Fenster
  theme_template: >
    if (entities['binary_sensor.climate_livingroom_windowshutter'].state === 'on') return 'yellow'; else return 'default';
  extra_data_template: >
     if (entities['binary_sensor.climate_livingroom_windowshutter'].state === 'off') return null; else return Seit (entities['sensor.climate_livingroom_windowshutter_openingtime'].state) Minuten offen;
  state_card_mode: badges
```

configuration.yaml
```yaml
frontend:
  extra_html_url:
    - /local/custom_ui/state-card-media_player.html
    - /local/custom_ui/state-card-custom-ui.html
    - /local/custom_ui/state-card-custom_alarm.html
    
  themes:
    yellow:
      label-badge-background-color: yellow
      label-badge-text-color: yellow
```

**Problem-relevant Home Assistant log entries:**
```
no applicable log entries observed
```

 
**Any errors from browser Javascript console:**
```
Uncaught SyntaxError: Unexpected identifier
    at new Function (<anonymous>)
    at Object.computeTemplate (state-card-custom-ui.html:1)
    at HTMLElement.computeExtra (state-card-custom-ui.html:1)
    at k (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at Object.d [as fn] (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at a (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at e (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at u (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at HTMLElement.value (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
    at HTMLElement.value (frontend-6b0a95408d9ee869d0fe20c374077ed4.html:1)
```

```
Uncaught TypeError: Cannot read property 'customizer.customizer' of null
    at Object.useCustomizer (state-card-custom-ui.html:1)
    at Object.init (state-card-custom-ui.html:1)
    at state-card-custom-ui.html:1
```
