### ISSUE TITLE
Need to force refresh before entities show (0.53.)

### ISSUE THREAD

**Issue by laurentdinclaux** [andrey-git/home-assistant-custom-ui#45]
I updated to 0.53 today and have empty state cards under Chrome desktop **and** mobile. 
In order to have the state cards content, I need to 
1) first open the console (F12)  
2) then force refresh (Ctrl + F5). 

**I have to do it each time I open home assistant**

Because it isn't possible to do on mobile, I cannot have it work on mobile.
Firefox has no such issue.

Looks like a duplicate of #40 

**Browser + Version:** Chrome 61

**CustomUI version:** 20170918

**Home Assistant:** 0.53.1

```
homeassistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui

customizer:
  custom_ui: local
```
