### ISSUE TITLE
Group specific friendly names not always working

### ISSUE THREAD

**Issue by scmmmh** [andrey-git/home-assistant-custom-ui#48]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser version:** Firefox - 56, Chrome - 61

**CustomUI version:** 20170927

**Home Assistant release (`hass --version`):** 0.55.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
group.living_room_lights:
  friendly_name: Living Room Lights
  icon: mdi:lightbulb
  group:
    group.living_room:
      friendly_name: Lights
sensor.living_room__aeotec_luminance:
  friendly_name: Living Room Light Level
  state_card_mode: badges
  group:
    group.living_room:
      friendly_name: Light Level
```

**`groups.yaml`:**

```yaml
Default View:
  view: yes
  icon: mdi:home
  entities:
    - group.living_room_lights
    - group.default_view_sensors
Living Room:
  view: yes
  entities:
    - group.living_room_sensors
    - group.living_room_lights
Living Room Lights:
  entities:
    - switch.living_room__corner_switch
    - switch.living_room__cabinet_switch
Living Room Sensors:
  entities:
    - binary_sensor.compound_living_room_occupancy
    - sensor.living_room__aeotec_temperature
    - sensor.living_room__philio_temperature
    - sensor.living_room__aeotec_luminance
```
 
**Any errors from browser Javascript console:**
```
Unable to check <input pattern='[[pattern]]'> because the pattern is not a valid regexp: raw bracket is not allowed in regular expression with unicode flag blank
paper-drawer-panel is deprecated. Please use app-layout instead!  frontend-2de1bde3b4a6c6c47dd95504fc098906.html-75.js:1
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]  group.living_room
Invalid chrome URI: /
Loaded CustomUI 20170927  state-card-custom-ui.html.js:1
```

The issue I am facing is that the context-aware attributes for groups seem to not always work. In particular it seems that elements that are nested directly in the group being used as a filter are not taking the context-aware aspects into account, while more deeply nested elements are.

In the "groups.yaml" above the first two groups define views in the interface. The second two groups that are then loaded into those two views. Groups or sensors/switches/... that are in one of the nested groups will take the context-aware aspects into account and as the configuration sample shows I use it to modify the `friendly_name`. For some reason the same does not work for groups/sensors/switches/... that are included directly in the view groups. The "Living Room Light Levels" to "Light Levels" works, but the "Living Room Lights" to "Lights" one does not.

I have some screenshots, but for some reason cannot upload them here. Will keep trying.
