### ISSUE TITLE
Not able to apply to the group of light

### ISSUE THREAD

**Issue by sumitrajancse** [andrey-git/home-assistant-custom-ui#50]
I am trying to customize the group of light so that each light has the following feature. But not able to..
group.all_lights:
  custom_ui_state_card: state-card-custom-ui
  show_last_changed: true
  state_card_mode: break-slider-toggle
  stretch_slider: true
  theme: happy
  slider_theme:
    max: 200
    min: 10
    off_when_min: false
    pin: true
    report_when_not_changed: false
group.all_devices:
    show_last_changed: true

This above code is from the customize.yaml file. Am I doing something wrong? 
If I do it for one entiity, it work fines

**Comment by andrey-git** [comment]
Your yaml is not formatted. Are you trying to apply CustomUI to all lights?
In that case use:
```
homeassistant:
  customize_glob:
    light.*:
      custom_ui_state_card: state-card-custom-ui
      ...
```
What you did applies the settings to the group itself.

**Comment by sumitrajancse** [comment]
Following is the configuration.yaml file
homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  
  # Customization file
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
  customize: !include customize.yaml

------------------------- Customize.yaml file:

sensor.linear_wapirz1_motion_sensor_temperature:
  friendly_name: Sala Temperature
  show_last_changed: true
  custom_ui_state_card: state-card-custom-ui
light.cree_connected_a19_60w_equivalent_fe03e539_10:
  friendly_name: Kitchen Light
light.osram_lightify_a19_rgbw_00a42028_3:
  friendly_name: Sala Light
  
light.cree_connected_a19_60w_equivalent_fe03e82d_10:
  friendly_name: Dinner Light
light.cree_connected_a19_60w_equivalent_fe03e7e9_10:
  friendly_name: Passage Light
group.all_lights:
  custom_ui_state_card: state-card-custom-ui
  show_last_changed: true
  state_card_mode: break-slider-toggle
  stretch_slider: true
  theme: happy
  slider_theme:
    max: 200
    min: 10
    off_when_min: false
    pin: true
    report_when_not_changed: false
group.all_devices:
  show_last_changed: true
group.scenes: {}

**Comment by andrey-git** [comment]
```
group.all_lights:
  custom_ui_state_card: state-card-custom-ui
  show_last_changed: true
  state_card_mode: break-slider-toggle
  stretch_slider: true
  theme: happy
  slider_theme:
    max: 200
    min: 10
    off_when_min: false
    pin: true
    report_when_not_changed: false
```
Doesn't do anything useful. It applies configuration to the `all_lights` **group**, while the configuration should be applied to the lights themselves.
Either one-by-one or via `customize_glob`
