### ISSUE TITLE
Theming and per entity theming not working for badges

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#51]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome, 62

**CustomUI version:** 
2017-10-19
**Home Assistant release (`hass --version`):** 
0.56.2
**Problem-relevant `configuration.yaml` entries:**

_**Everything else works OK (regarding themes and per entity themes). I can set a theme for all of them, however not per entity.
The variables below are ignored by Custom-UI. I didn't try but I am sure all the variables are ignored for the badges (badges can't be themed). Am I doing something wrong?**_
```
--label-badge-background-color: white;
--label-badge-text-color: rgb(76, 76, 76);
```
Sample configuration:
```yaml
binary_sensor.door_window_sensor_158d0000f125f7:
      state_card_mode: badges
      templates:
        theme: >
            if (entity.state == 'on') return 'statuson'; else return 'default';

statuson:
      label-badge-background-color: '#00cc66'
      label-badge-text-color: rgb(76, 76, 76);
```

**Problem-relevant Home Assistant log entries:**
```
No errors in log.
```

**Any errors from browser Javascript console:**
```
See picture below.
```
![image](https://user-images.githubusercontent.com/8059190/32118407-e5c989da-bb51-11e7-8943-306ce3f6f0c5.png)

![image](https://user-images.githubusercontent.com/8059190/32118024-978747fe-bb50-11e7-9102-57f64385a3a0.png)
