### ISSUE TITLE
Allow glob in device and group specifiers of context aware attributes

### ISSUE THREAD

**Issue by mhofman** [andrey-git/home-assistant-custom-ui#55]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 63.0.3239.40

**CustomUI version:** 20171117

**Home Assistant release (`hass --version`):** 0.58.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
domain.object_id:
  device:
    person_*:
      attr1: abc

  group:
    group.glob_*:
      attr2: def
```

It would be great to allow glob patterns in the selection of device / group names for the context override feature.
