### ISSUE TITLE
Hide sensor from top row in homeassistant when using extra_badge without losing logging?

### ISSUE THREAD

**Issue by CaptInsano** [andrey-git/home-assistant-custom-ui#59]
### Checklist
- [ Yes] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [ Yes] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [ Yes] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 
Chrome 62 Desktop
Firefox 57 Desktop
Chrome 62 Android

**CustomUI version:** Custom UI 20171129

**Home Assistant release (`hass --version`):** 0.59.2

**Problem-relevant `configuration.yaml` entries:**
```
customizer:
  custom_ui: local

........ in groups.yaml......

heating:
  name: Heating
  entities:
    - switch.heatinggf
    - switch.heating1f
    - switch.heating2f
    - switch.heatinghw

........ in customize.yaml.......

switch.heatinggf:
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.temperature_158d0001b95304
  friendly_name: Ground Floor Heating
  icon: mdi:radiator
switch.heating1f:
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.temperature_158d0001b952a3
  friendly_name: 1st Floor Heating
  icon: mdi:radiator
switch.heating2f:
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.temperature_158d0001b92a4e
  friendly_name: 2nd Floor Heating
  icon: mdi:radiator

sensor.temperature_158d0001b952a3:
  friendly_name: Living Room Temp
  hide: true
sensor.temperature_158d0001b92a4e:
  friendly_name: Bedroom Temp
  hide: true
sensor.temperature_158d0001b95304:
  friendly_name: Ground Floor Temp
  hide: true

```

**Problem-relevant Home Assistant log entries:**
```
no probs in log
```

**Any errors from browser Javascript console:**
```
no errors in console
```

What I want: I want to have sensors as extra badges in a "Heating" group card as shown above and I want those sensors hidden from the top row of sensors in Homeassistant.

Problem: When I set "hide: true" in customize it correctly hides the sensor from the top row in homeassistant and shows it only in the group card BUT it also disables the logging/history for the sensor. If I click on the badge in the group card, I get a "no state history found" error instead of a graph.

Is there any way of hiding the sensor from the top rowafter using extra_badge WITHOUT losing logging/history?

Thanks

**Comment by CaptInsano** [comment]
Further note: 
If I remove "hide:true" from each sensor in customize.yaml, the logging/history works but I end up with the sensor listed in the group card  as extra_badge AND in the top row of homeassistant.

**Comment by fanaticDavid** [comment]
If I understand correctly what you're trying to achieve, you would have to override the `default_view` group so you have full control over what shows up in the UI. Of course, that means entities wouldn't get added to your UI automatically anymore, it would all have to be "hard coded".

For more information, check the [group docs](https://home-assistant.io/components/group/).

**Comment by andrey-git** [comment]
Sensors disappear from top view if the are part of some group.

Add the 3 temperature sensors to Heating group and then hide them using context-aware hide.

**Comment by CaptInsano** [comment]
I edited my groups.yaml to include the following:

```
heating:
  name: Heating
  entities:
    - sensor.temperature_158d0001b95304
    - switch.heatinggf   
    - switch.heating1f
    - switch.heating2f
    - switch.heatinghw
```

and my customize.yaml to include:
```

sensor.temperature_158d0001b95304:
  custom_ui_state_card: state-card-custom-ui
  friendly_name: Ground Floor Temp
  group:
    group.heating:
      hidden:true
```

But the entry is not hidden in the heating group (it created a full new line for the Temp sensor), I have obviously misunderstood some of the context aware readme. Any advice?
