### ISSUE TITLE
Lock icon only shows on one button in Cover

### ISSUE THREAD

**Issue by uchagani** [andrey-git/home-assistant-custom-ui#66]
The lock icon from ```confirm_controls_show_lock: true``` only shows up on one button of the cover buttons.  Not sure if this is expected behavior or not.

![image](https://user-images.githubusercontent.com/1053584/34344269-12b29890-e9b2-11e7-83b4-6bcca88b2e0d.png)

### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** 63.0.3239.108 

**CustomUI version:** 20171224

**Home Assistant release (`hass --version`):** 0.60.0

**Problem-relevant `configuration.yaml` entries:**
```yaml
cover.garage_door:
  confirm_controls_show_lock: true
  custom_ui_state_card: state-card-custom-ui
  extra_data_template: ${state}
  friendly_name: Garage Door
  slider_theme:
    max: 100
    min: 0
    off_when_min: false
    pin: true
    report_when_not_changed: false
  state_card_mode: break-slider
  stretch_slider: true
  theme: happy
```
