### ISSUE TITLE
please add option for  more than one slider

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#69]
you're fast!
I've just edited #68 but you've already implemented and closed......

thanks for that, ill repost my extra issue (read request) here:

wishlist part 2:

if we could have more than one slider, things would get even better. Im imagining a setup where I wouldn't have to click the light to go to the sliders and change them. Have the custom-ui allow for a multiple slider setup would not force us to do so, and have all controls needed and wanted in 1 majestic view.....
I know, I am asking a lot, but really really hope this would be an option for the development of Custom-ui.
----- end edit -----
Cheers,
Marius

**Comment by andrey-git** [comment]
I responded to that in #68 
This doesn't scale to implement multiple nicely-wrapping sliders. If you just want to add slider-per-line you can do so with input_slider component that will send commands to your light.

**Comment by hvbhome** [comment]
ok thanks, not sure i fully comprehend yet, but ill check.

Right now the new version doesn't show my array of extra-data template, and even took out the first grey data. Is my syntax no correct?:

```
light.bureau:
  extra_data_template: >-
    - if (attributes.brightness) return attributes.brightness + 'B'; return null;
    - if (attributes.color_temp) return attributes.color_temp + 'C'; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: false
    report_when_not_changed: false
  extra_badge:
    - attribute: brightness
    - attribute: color_temp

```
What would be the code to have 2 sliders showing? one for brightness and one for color?

Thanks!
Marius

**Comment by andrey-git** [comment]
Remove `>-`

**Comment by hvbhome** [comment]
cool!

![schermafbeelding 2017-12-27 om 12 35 47](https://user-images.githubusercontent.com/33354141/34380539-8c6ed5e4-eb02-11e7-9259-33f6ad8df6d2.jpg)

Now the only thing left is showing these values next to each other instead of on top of each other... Saves space! And follows the visual effect of the slider, looking from left to right.
Love this.
Cheers,
Marius

**Comment by andrey-git** [comment]
To show values next to each other you don't even need the last update, as you control the text completely.
```
extra_data_template:
    - if (attributes.brightness || attributes.color_temp) return (attributes.brightness ? attributes.brightness + 'B' : '') + (attributes.color_temp ? attributes.color_temp + 'C' : ''); return null;
```

**Comment by hvbhome** [comment]
never thought of that... of course. Thx.

btw, is there a preference in the code you use over the example I presented, and if so, why is that?. I thought to have used your own instruction syntax, but now you've changed from:

```
extra_data_template: >-
    - if (attributes.brightness) return attributes.brightness + 'B'; return null;

```
to

```
extra_data_template:
    - if (attributes.brightness || attributes.color_temp) return (attributes.brightness ? attributes.brightness + 'B' : '')
```
Marius

**Comment by andrey-git** [comment]
Try to quote the template string. I think Yaml doesn't like the ':'

**Comment by hvbhome** [comment]
hi Andrey,
not sure what you're instructing me here, but i tried quoting the full string, and it showed, well,  the full string in the frontend.....

if yaml doesn't like the ': ', what does it leave me to do then? go back to the definition with 'return null' ? i tried that, but apparently did it wrong, because it showed noting at all.
Please have a look, and i hope you can document the correct syntax in the custom-ui instructions.

Thanks for that,
Marius

**Comment by andrey-git** [comment]
```
extra_data_template:
    - "if (attributes.brightness || attributes.color_temp) return (attributes.brightness ? attributes.brightness + 'B' : '')"
```

**Comment by hvbhome** [comment]
thanks, but that doesn't work:

![schermafbeelding 2017-12-27 om 20 30 10](https://user-images.githubusercontent.com/33354141/34391265-d4f26aaa-eb44-11e7-98a3-00b831739a11.jpg)


code:
```
light.bureau:
  extra_data_template:
    - if (attributes.brightness) return attributes.brightness + 'B'; return null;
    - if (attributes.color_temp) return attributes.color_temp + 'C'; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: false
    report_when_not_changed: false
  extra_badge:
    - attribute: brightness
    - attribute: color_temp

light.inside:
  extra_data_template:
    - "if (attributes.brightness || attributes.color_temp) return (attributes.brightness ? attributes.brightness + 'B' : '')"
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: false
    report_when_not_changed: false
  extra_badge:
    - attribute: brightness
    - attribute: color_temp

```
