### ISSUE TITLE
Unit_of_measurement - Badge 'belt' not displayed? feature request.

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#71]
HI,

Done we need to declare the unit_of_measurement of the extra_badges specifically in certain domains?

I just realized that the badges in eg these light customizers don't show their u_o_m belts:

![schermafbeelding 2017-12-28 om 10 00 07](https://user-images.githubusercontent.com/33354141/34405858-efa64ac6-ebb5-11e7-8667-d9d6066a6b14.jpg)

```
light.bedside_table:
  extra_data_template: > 
    if (attributes.color_temp) return attributes.color_temp + ' C'; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: false
    report_when_not_changed: false
  extra_badge:
    - attribute: brightness
    - attribute: color_temp

```
while these do, without any special code, other than the extra badges poiting to a sensor:

![schermafbeelding 2017-12-28 om 10 01 04](https://user-images.githubusercontent.com/33354141/34405876-0ff24e10-ebb6-11e7-8cf7-cd8d5d8f626b.jpg)

```
switch.sw_audio_auditorium_cl:
  icon: mdi:speaker
  confirm_controls_show_lock: true
  extra_badge:
    - entity_id: sensor.audio_auditorium_actueel
    - entity_id: sensor.audio_auditorium_totaal

```

Would be very nice to have the u_o_m displayed in the lights domain too, or anywhere else for that matter.

Cheers,
Marius
