### ISSUE TITLE
Option to show extra_data_template and show_last_changed at the same time (array) and other question

### ISSUE THREAD

**Issue by covrig** [andrey-git/home-assistant-custom-ui#72]
I noticed that in the latest version (2017-12-27) we have the option to display several rows of data in the `extra_data_template` section. Could it be feasible to include the `show_last_changed` in the array? From what I read, now we can't have both features in the same time for a single entity.

Also is it possible to show only badges (extra badges) in the state card? Everything should be a badge, including the entity state?
![image](https://user-images.githubusercontent.com/8059190/34435371-54a154d4-ec8d-11e7-8f54-4e56e63e0b91.png)

**Comment by andrey-git** [comment]
You can already do this:
1) Add state as badge just like you add any badge via 
```
extra_badge:
  entity_id:
```
2) Remove the state label by
```
hide_control: true
```

**Comment by covrig** [comment]
Thank you for your answer.
I just realized that I can use the `show_last_changed` and `extra_badge` together without any problem. This is what I wanted.

However, I have a new question. Obviously if I add multiple _extra badges_ they will all take the theme of the parent entity (even if they have their own theme setup). Would it be possible to have each badge using a different theme (retrieving its theme setup)? I can see that we can already click on each badge and retrieve their own history graph.

In my case one badge should be blue and the other red (different alarms.. blue under 10C and red over 75% humidity). The humidity badge is retrieving the temperature theme.

![image](https://user-images.githubusercontent.com/8059190/34455339-779d373c-ed7d-11e7-8e3f-700ab4680c4d.png)

Thank you for your work.

**Comment by hvbhome** [comment]
HI @covrig 

Im very interested in your setup, so if you make it, would you care to share the code for these sensors and group?

btw, you have the last_changed and extra_badges now, which is what i use in my lights setup extensively, very nice indeed!.
but would it be also possible to have the array of last_changed and extra_data? your first question? id be keen to know the answer and check what that looked like.

Cheers,
Marius

**Comment by andrey-git** [comment]
last_changed and extra_data are not supported together. You can emulate last_changed via extra_data JavaScript yourself.

**Comment by covrig** [comment]
@hvbhome I am not interested in the `show_last_changed` and `extra_data_template`. I was wondering if it is possible using directly CustomUI. 
However, you can always create an additional template sensor in HASS retrieving the `last_updated` value of the sensor you need (`'{{relative_time(states.sensor.example.last_updated)}}'`) and add it to the `extra_data_template` array inside CustomUI (`extra_data_template: entities['sensor.template_example'].state`).
Regarding the code for the sensors it is simple.
```
    sensor.avg_temperature:
      show_last_changed: true
      hide_control: true
      extra_badge: 
        - entity_id: sensor.avg_humidity
        - entity_id: sensor.avg_temperature
      templates:
        theme: >
            if (entity.state >= 25) return 'red'; else if (entity.state >= 2 && entity.state < 7) return 'blue'; else if (entity.state < 2) return 'bluewhite'; else return 'default';
```
```
  themes:
    red:
      primary-text-color: red
      paper-card-background-color: '#fcbba1'
      paper-item-icon-color: red
      secondary-text-color: red
      label-badge-background-color: '#fcbba1'
      label-badge-text-color: red
      etc...
```

**Comment by hvbhome** [comment]
Cool! I was indeed looking for a red alert like that !

Please share the code for that flicker alert would you?
Very eye catching and necessary for several always-on appliances I have...

![7e87eaf4-b8f3-4b69-ac80-ff650a6606a5](https://user-images.githubusercontent.com/33354141/34461199-c0c0cec2-ee24-11e7-828a-abf98cd6c183.png)

**Comment by hvbhome** [comment]
HI,

Thanks for the above info on theming, i've solved my question though, so don't bother.

I woud still love to hear from you about the blinking alarms , and hope you can share some code on that.
If this is not the place to elaborate on the issue, please excuse me, and maybe let me take this elsewhere?
Cheers,
Marius

![Uploading Schermafbeelding 2018-01-01 om 20.45.33.jpg…]()

**Comment by fanaticDavid** [comment]
I'm also interested in showing `extra_data_template` and `show_last_changed` at the same time. Shouldn't these options be made compatible now considering having more than 1 line (an array) is now also possible? Anyway, this is the closest I got (which isn't very close 😛 ):

<img width="414" alt="schermafbeelding 2018-01-01 om 16 41 43" src="https://user-images.githubusercontent.com/20402931/34474809-9a77cd86-ef84-11e7-88b1-62280b80ea9f.png">

```yaml
sensor.dsm_memory_usage_real:
  friendly_name: "RAM use"
  extra_data_template:
    - ${'of ' + Math.round(entities['sensor.dsm_memory_size'].state) + ' ' + entities['sensor.dsm_memory_size'].attributes.unit_of_measurement.toUpperCase()}
    - ${entity.last_changed}
```

I'm a JavaScript beginner at best so I can't figure out the JavaScript counterpart for Jinja2's `relative_time(timestamp)` template.
