### ISSUE TITLE
entity name left above slider?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#73]
HI Andrey,

Ive been playing around with the many options you've given us. And I think it is amazing, and getting better with each iteration.

Ive come up with a setting I rather like, with the wish for 1 extra possibility. Maybe it is already possible, but I havent found it then.

Please check this Hall Lights: Keyboard configuration, very nice and compact, I feel it to be as condensed and yet useful as possible, with one caveat: the entity name is cutoff (as is the last changed value) . Which is kind of necessary since there simple isnt enough horizontal space.
Thats why i would like to ask you if we could place the entity friendly name above the slider, top left, with all other items like they are, a beautiful slim line. Maybe find a way for the last changed to shoe unabridged too?

```
light.keyboard:
  state_card_mode: single-line
  stretch_slider: false
  hide_control: false
  show_last_changed: true
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: true
    report_when_not_changed: true
  extra_badge:
    - attribute: brightness
    - attribute: color_temp  

```
![schermafbeelding 2017-12-29 om 15 54 01](https://user-images.githubusercontent.com/33354141/34439835-22b83afe-ecb1-11e7-9fb6-beca9ac86a0c.jpg)

If you compare with the Corridor lights to the left, you see how much thicker this looks, without having a lot more info.

Maybe you have an option or idea how the realize. If not, no first world problem of course, just asking here..

Cheers, thanks for your time!

Marius
