### ISSUE TITLE
cards showing black background??

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#74]
HI,

My cards are now all showing a black background... What could be the reason for this? Ive had a dark blue setting after 21 hours, but set it to default now. still showing black.

![schermafbeelding 2017-12-31 om 00 50 52](https://user-images.githubusercontent.com/33354141/34458071-e7d0263a-edc4-11e7-93b9-867205e7213e.jpg)

code:

```
light.gamer_den:
  state_card_mode: break-slider
  stretch_slider: true
  extra_data_template:
    if (attributes.color_temp) return attributes.color_temp + ' C' ; return null;
  hide_control: false
  show_last_changed: false
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: true
    report_when_not_changed: true
  extra_badge:
    - attribute: brightness
      unit: Br
#    - attribute: color_temp
#      unit: Co

light.keyboard:
#    extra_data_template: >
#    if (attributes.color_temp) return attributes.color_temp + ' C' ; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: true
  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: true
    report_when_not_changed: true
  extra_badge:
    - attribute: color_temp
      unit: Co
    - attribute: brightness
      unit: Br
```
---edit---

i sus[ect it had to do with the fact that on my phone i had selected a night theme.. Strange this had effect on my macbook with the default theme?

----
