### ISSUE TITLE
extra_data_template not working

### ISSUE THREAD

**Issue by paulbdavis** [andrey-git/home-assistant-custom-ui#80]
### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Firefox 57.0.4 and Chrome 63.0.3239.108

**CustomUI version:** 20171227
**Home Assistant release (`hass --version`):** 0.60.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
script.feed_cats:
  icon: mdi:cat
  custom_ui_state_card: state-card-custom-ui
  extra_data_template:
    - FOO
    - '${attributes.last_triggered}'
```
The above configuration does not work, nothing shows up extra in the UI. Using `show_last_changed: true` instead *does* work.

EDIT: The `extra_data_template` option *does* work when I use it on a light, but not on on a script
EDIT 2: Also works on a switch, so I guess I just need to figure out how to get it to work on a script
