### ISSUE TITLE
Show_last_changed for Group?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#86]
HI,

Maybe i am having sight problems... but is it in any way possible to use the show_last_changed on a group.
Example:

Group of lights triggered by a motion sensor.

![schermafbeelding 2018-01-18 om 10 52 33](https://user-images.githubusercontent.com/33354141/35091819-fcfad42e-fc3d-11e7-8b03-7ee9543feb47.jpg)

right now i show the last changed on one of the lights, but would rather show its RGB attributes there (too big for a badge) and the color_temp and brightness in the badges.

If one could show the last_changed of the group, one could use the other options for the separate entities and use Card space super efficiently.

```
light.drawer:
  extra_data_template:
    if (attributes.rgb_color) return "RGB:" + attributes.rgb_color ; return null;
  state_card_mode: break-slider
  stretch_slider: true
  hide_control: false
  show_last_changed: true
#  theme: happy
  #confirm_controls_show_lock: true
  slider_theme:
    min: 0
    max: 255
    pin: true
    off_when_min: true
    report_when_not_changed: true
  extra_badge:
    - attribute: color_temp
      unit: Co
    - attribute: brightness
      unit: Br
```

and hopefully:

```
group.hallway_lights:
  show_last_changed: true

```

![schermafbeelding 2018-01-18 om 10 59 23](https://user-images.githubusercontent.com/33354141/35092129-bbaf13ee-fc3e-11e7-98c0-5a4ef04ef65e.jpg)

Cheers,
Marius
