### ISSUE TITLE
Hide sensors without losing logging

### ISSUE THREAD

**Issue by ruippeixotog** [andrey-git/home-assistant-custom-ui#87]
### Checklist
- [X] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [X] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [X] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 63

**CustomUI version:** 20171227

**Home Assistant release (`hass --version`):** 0.60.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
homeassistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    device_tracker.*:
      group:
        group.away_devices:
          hidden: true
```

**Problem-relevant `customize.yaml` entries:**
```yaml
group.away_devices:
  # hidden: true
  templates:
    entity_id: >
      return Object.keys(entities).filter(key =>
        key.indexOf("device_tracker.") == 0 && entities[key].state === 'not_home');
```

This is a variation of #59 without using extra_badge. I'm trying to work around https://github.com/home-assistant/home-assistant/issues/11353 / https://github.com/home-assistant/home-assistant/issues/11564 - being able to hide from the UI tracked devices with a "not home" status without losing history and logging from those entities. I created a dynamic group with all such devices and I used the context-aware hide to make all the devices inside the group invisible.

This all worked as expected, but I ended up with an empty "Away Devices" card in my dashboard. I tried to hide the group too (the commented section in the config above), but if I hide the group all away devices appear again on the top, "ungrouped" bar.

Is this the expected behavior of custom-ui? Is there any way to do what I'm trying to do?

**Comment by andrey-git** [comment]
If you want to hide the devices unconditionally, but without the backend knowing about it - use templates:
```yaml
homeassistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    device_tracker.*:
      templates:
        hidden: true
```

**Comment by ruippeixotog** [comment]
Thanks for the quick response! I would not like to hide all tracked devices unconditionally, only those that have a state of "not home". That's the reason why I had to create an auxiliary group.

**Comment by andrey-git** [comment]
```yaml
homeassistant:
  customize_glob:
    "*.*":
      custom_ui_state_card: state-card-custom-ui
    device_tracker.*:
      templates:
        hidden: "if (state === "not_home") return true; else return null;"
```
Please check how the "not home" state really looks like.
