### ISSUE TITLE
Best way to round numbers using templates?

### ISSUE THREAD

**Issue by fanaticDavid** [andrey-git/home-assistant-custom-ui#88]
I don't think I have an issue to report, I'm just trying to figure out the correct or best way to round numbers using Custom UI's templates.

The following bit of code works:
```yaml
sensor.host_ups_load:
  friendly_name: "Load"
  icon: mdi:speedometer
  templates:
    _stateDisplay: return Math.round(state) + ' ' + attributes.unit_of_measurement;
```
This is awesome because it eliminates my need for template sensors just to round the state of other sensors!

Originally, I tried it like this but it was causing strange behaviour (entity list would get stuck loading, filtering wouldn't work properly once it did, errors in the browser console, etc.):
```yaml
sensor.host_ups_load:
  friendly_name: "Load"
  icon: mdi:speedometer
  templates:
    state: return Math.round(state);
```
The advantage of this template is that the unit of measurement is maintained without me having to specify it. But I'm assuming I'm creating some logical loop with this template which would explain the strange behaviour.

Am I doing this the right way already? Or is there a simpler way after all?
