### ISSUE TITLE
Show in more info but not in regular view

### ISSUE THREAD

**Issue by mhofman** [andrey-git/home-assistant-custom-ui#90]
**Browser + Version:** Chrome 64

**CustomUI version:** 20180117

**Home Assistant release (`hass --version`):** 0.61.1

**Problem-relevant `configuration.yaml` entries:**
```yaml
input_boolean.tie_nest_away_mode_to_phones_presence:
  custom_ui_state_card: state-card-custom-ui
  group:
    group.climate:
      hidden: true
```

I'd like to show certain group items only in the more-info overlay, and not in the main view.
The use case is to make "configuration" inputs and other detailed sensor info visible only when going into more detail, but hide them from the more view which contains a clean overview.

Right now, hiding them using group overrides also hides them in more-info. I'm not familiar enough with the HA polymer code to know if or what exactly would be doable.
If it's possible to compute a different state in the main view and in more info, maybe custom-ui could expose a variable in templates indicating where the element is.

Something like this:
```yaml
input_boolean.tie_nest_away_mode_to_phones_presence:
  custom_ui_state_card: state-card-custom-ui
  group:
    group.climate:
      templates:
        hidden: "return inMainView === true"
```
