### ISSUE TITLE
JS Error in dev-state panel

### ISSUE THREAD

**Issue by cicero200272** [andrey-git/home-assistant-custom-ui#91]
My dev-state panel does not load any more but throws a JS exception. Issue started a few updates of custom-ui ago and is definitely related to it. When I remove the customizer in my configuration.yaml, everything works fine. 

### Checklist
- [x] I'm running the latest version of CustomUI ([Update guide](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/installing.md#updating)) or using a specific [release](https://github.com/andrey-git/home-assistant-custom-ui/releases) that is not marked as "Broken".
- [x] I tried to force-refresh (Ctrl+Shift+R / Ctrl+F5) the browser
- [x] (Optional, but recommended) I'm using Chrome or tried to reproduce the feature on Chrome.

**Browser + Version:** Chrome 64

**CustomUI version:** 20180117 

**Home Assistant release (`hass --version`):**  0.61.1

**Problem-relevant `configuration.yaml` entries:**
```
customizer:
  custom_ui: local
  hide_attributes:
    - time
    - date
    - scan_interval
    - gps_accuracy
    - source_type
    - battery
    - provider
    - direction
    - speed
    - attribution
    - activity
    - is_hue_group
    - state
```

**Problem-relevant Home Assistant log entries:**
none

**Any errors from browser Javascript console:**
![js_error](https://user-images.githubusercontent.com/15817602/35435427-fe8841de-028a-11e8-8551-33168cc43234.png)
