### ISSUE TITLE
feature request: script as 'extra_badge'

### ISSUE THREAD

**Issue by Mariusthvdb** [andrey-git/home-assistant-custom-ui#92]
HI,

Please consider having the possibility for a script as an extra option for the extra_badges, like so:

```
switch.sw_tester_template:
  extra_badge:
  - entity_id: sensor.tester_actueel
  - entity_id: sensor.tester_totaal
  - entity_id: script.sw_tester_force_off
```

scripting this case being:

```
sw_tester_force_off:
  alias: "7 - Tester Off"
  sequence:
    - service: switch.turn_off
      data:
        entity_id: switch.sw_tester_cl
```

The extra-badge would need to be a 'button' (not a sensor badge with a value) to click for the command to be issued.

In my case above i need the extra forced_off command , without checking states the regular on/off switches have.
Other commands might also be thinkable, like a forced state command, which is especially useful when an mqtt command doesn't stick for some reason.

**Comment by hvbhome** [comment]
please let me get back on this before you contemplate ;-)

ive created the extra badges above, and this works out alright. It shows the badge and clicking the badge give a more-info, where i can activate the script. Actually this is even better than i first envisioned, because it gives a way of second thought. Running the scripts point blank might be dangerous.

What would really be nice is if we could change the Badge into a (smaller) button, eg mdi:power. Would this be possible through the Custom-ui?

Ive tried it with below customization, unfortunately without the desired effect:

```
switch.sw_tester_template:
  icon: mdi:test-tube
  show_last_changed: true
  extra_badge:
    - entity_id: script.sw_tester_force_off
    - entity_id: sensor.tester_actueel
    - entity_id: sensor.tester_totaal

script.sw_tester_force_off:
  icon: mdi:power
```

![schermafbeelding 2018-01-31 om 20 54 01](https://user-images.githubusercontent.com/33354141/35644418-2be59f0e-06c9-11e8-8013-ab793251f51c.jpg)

Hope you can have a look,
Cheers,
Marius
