### ISSUE TITLE
[Feature request] Add extra_data_template for switch domain

### ISSUE THREAD

**Issue by emilp333** [andrey-git/home-assistant-custom-ui#96]
Hi,

I have a lot of switches that reports power_consumption. Please add the extra_data_template option for switch domain as for light domain.

Cheers!

**Comment by fanaticDavid** [comment]
I believe switches are already supported. The documentation says you can use `extra_data_template` with the following 4 types of cards:

* Light
* Cover,
* "Plain" i.e. card with icon, name, and state.
* "Toggle" i.e. card with icon, name, and toggle.

A switch is a toggle.

**Comment by hvbhome** [comment]
they are supported:

![schermafbeelding 2018-02-03 om 20 26 37](https://user-images.githubusercontent.com/33354141/35770711-971772bc-0920-11e8-9319-2eac7e4b7b4c.jpg)

```

switch.sw_audio_auditorium_template:
  icon: mdi:speaker
  show_last_changed: true
  confirm_controls_show_lock: true
  extra_badge:
    - entity_id: script.sw_audio_auditorium_force_off
    - entity_id: sensor.audio_auditorium_actueel
    - entity_id: sensor.audio_auditorium_totaal

switch.sw_tv_auditorium_template:
  icon: mdi:television
  show_last_changed: true
#  confirm_controls_show_lock: true
  extra_badge:
    - entity_id: script.sw_tv_auditorium_force_off
    - entity_id: sensor.tv_auditorium_actueel
    - entity_id: sensor.tv_auditorium_totaal

```
